Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt
from matplotlib.patches import ConnectionStyle
import networkx as nx

# Graph„Ç™„Éñ„Ç∏„Çß„ÇØ„Éà„ÅÆ‰ΩúÊàê
DG = nx.DiGraph()
DG.add_edge(0, 1)
DG.add_edge(0, 3)
DG.add_edge(1, 3)
DG.add_edge(2, 3)
DG.add_edge(2, 4)
DG.add_edge(4, 5)

options = {
    "font_size": 10,
    "node_size": 400,
    "node_color": "white",
    "edgecolors": "black",
    "linewidths": 2,
    "width": 2,
}

# „ÇΩ„Éº„ÉàÂâç„ÅØÈÅ©ÂΩì„Å´ÈÖçÁΩÆ
pos_before = {0: (-3, 0), 1: (0, 0), 2: (-1, 0.3), 3: (2, 0.17), 4: (4, 0.255), 5: (5, 0.03)}
# „Éà„Éù„É≠„Ç∏„Ç´„É´„ÇΩ„Éº„ÉàÂæå„ÅÆÈÖçÁΩÆ
pos_after = {0: (0, 0), 1: (8, 0), 2: (16, 0), 3: (24, 0), 4: (32, 0), 5: (40, 0)}


# ax = plt.gca()
# ax.margins(0.20)
# plt.axis("off")
# plt.show()

# „Éà„Éù„É≠„Ç∏„Ç´„É´„ÇΩ„Éº„ÉàÂâçÂæå„Çí‰∫å„Å§‰∏¶„Åπ„Çã
fig = plt.figure(figsize=(10, 3))
# Â∑¶
ax1 = fig.add_subplot(1, 2, 1)
ax1.set_title('before')
ax1.set_axis_off()
ax1.margins(0.2)
nx.draw_networkx(DG, pos=pos_before, ax=ax1, **options)
# Âè≥
ax2 = fig.add_subplot(1, 2, 2)
ax2.set_title('after')
ax2.set_axis_off()
ax2.margins(0.2)
nx.draw_networkx(DG, pos_after, ax=ax2, **options, connectionstyle="arc3, rad=1")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 3>[0;34m()[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpatches[39;00m [38;5;28;01mimport[39;00m ConnectionStyle
[0;32m----> 3[0m [38;5;28;01mimport[39;00m [38;5;21;01mnetworkx[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnx[39;00m
[1;32m      5[0m [38;5;66;03m# Graph„Ç™„Éñ„Ç∏„Çß„ÇØ„Éà„ÅÆ‰ΩúÊàê[39;00m
[1;32m      6[0m DG [38;5;241m=[39m nx[38;5;241m.[39mDiGraph()

[0;31mModuleNotFoundError[0m: No module named 'networkx'
ModuleNotFoundError: No module named 'networkx'

